# ui

name: Deploy ui

env:
  APP_LOCATION: "public" # location of your client code

on: [push]

permissions:
  issues: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x.x
      - run: |
          dotnet tool restore
          npm install -g npm
          npm ci
          npm run build
          dotnet fable src
    
      # - name: Deploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.APP_TOKEN }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     action: "upload"
      #     app_location: ${{ env.APP_LOCATION }}
      #     skip_app_build: true